-- MySQL Script generated by MySQL Workbench
-- Mon 13 Oct 2014 11:58:44 AM CEST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fritzpay_payment
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fritzpay_payment` ;
CREATE SCHEMA IF NOT EXISTS `fritzpay_payment` DEFAULT CHARACTER SET utf8mb4 ;
-- -----------------------------------------------------
-- Schema fritzpay_principal
-- -----------------------------------------------------
USE `fritzpay_payment` ;

-- -----------------------------------------------------
-- Table `fritzpay_payment`.`config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fritzpay_payment`.`config` ;

CREATE TABLE IF NOT EXISTS `fritzpay_payment`.`config` (
  `name` VARCHAR(64) NOT NULL,
  `last_change` DATETIME NOT NULL,
  `value` VARCHAR(255) NULL,
  PRIMARY KEY (`name`, `last_change`))
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO paymentd;
 DROP USER paymentd;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'paymentd';

GRANT SELECT, INSERT ON TABLE fritzpay_payment.* TO 'paymentd';
GRANT SELECT, INSERT ON TABLE fritzpay_principal.* TO 'paymentd';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
